FlySwift/urls.py
from django.contrib import admin
from django.urls import path, include
from flight.views import index

urlpatterns = [
    path("", index, name="main page"),
    path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('ticket/', include('ticket.urls')),
    path('flight/', include('flight.urls')),
]

flight/urls.py
from django.urls import path

from flight import views

app_name = "flight"

urlpatterns = [
    path('', views.index, name='feed'),
    path("all/", views.FlightListView.as_view(), name="all_flights"),
    path("search/", views.search_flights, name="search_flight"),
    path('detail/<int:flight_id>', views.FlightView.as_view(), name="each_flight_page"),
    path("create/", views.FlightCreateView.as_view(), name="create_flight"),
    path("user_tickets/", views.user_tickets, name="user_tickets"),
    path("create/airport/", views.create_airport, name="create_airport"),
    path("create/airplane/", views.CreateAirplaneView.as_view(), name="crate_airplane"),
    path('search/date/', views.search_flights_byDate, name="search_flight_by_date"),
    path("allFlight/", views.getAllFlightrest.as_view(), name="all_flight_by_rest"),
    path("specificFlight/", views.search_flight_byDate_api.as_view(), name="get_specific_flights"),
]

ticket/urls.py
from django.urls import path

from .views import list_tickets, buying_ticket_page, cancelTicket, list_record_of_tickets, TicketDetailView, \
    TicketDetailViewAll, CheckTicket

app_name = "ticket"
urlpatterns = [
    path('all/', list_tickets, name="list_of_all_ticket_for_user"),
    path('buy/<int:fpk>/', buying_ticket_page.as_view(), name='buying_ticket'),
    path("cancel/<int:tpk>/", cancelTicket.as_view(), name="cancel_ticket"),
    path("record/", list_record_of_tickets, name="record_of_tickets"),
    path('ticket/<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('check/', CheckTicket.as_view(), name="check_ticket")
]

user/urls.py
from django.urls import path

from user.views import UserSignUp, Logout, Login, ChargingAccount, user_info

app_name = "user"

urlpatterns = [
    path('signup/', UserSignUp.as_view(), name="signup"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('charge/', ChargingAccount.as_view(), name="charging_account"),
    path('profile/', user_info.as_view(), name='profile'),
]

templates/footer.html
<footer class="footer mt-auto py-3 bg-dark text-white position: fixed; bottom: 0; width: 100%;">
    <div class="container">
        <span class="text-muted">&copy; Copyright 2024 SkySwift App</span>
    </div>
</footer>

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Flight App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, sans-serif;
            min-height: 100vh; /* Ensure at least 100% viewport height */
            position: relative
        }

        header {
            background-color: #333;
            color: white;
            padding: 10px;
            text-align: center;
        }

        nav a {
            color: white;
            text-decoration: none;
        }

        footer {
            background-color: #333;
            color: white;
            padding: 10px;
            text-align: center;
            position: fixed;
            bottom: 0;
            width: 100%;
        }

        .content {
            padding-bottom: 60px; /* Adjust the padding to accommodate the fixed footer height */
        }

        .content {
            padding-bottom: 60px; /* Adjust the padding to accommodate the fixed footer height */
            /* Additional styles */
        }
    </style>
</head>
<body>

<header class="container">
    <h1>My Flight App</h1>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div

                class="container-fluid">


            <a

                    class="navbar-brand"

                    href="#">Flight App</a>


            <button

                    class="navbar-toggler"

                    type="button"

                    data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"

                    aria-controls="navbarSupportedContent"

                    aria-expanded="false"

                    aria-label="Toggle navigation">


<span

        class="navbar-toggler-icon"></span>


            </button>


            <div

                    class="collapse navbar-collapse"

                    id="navbarSupportedContent">


                <ul

                        class="navbar-nav me-auto mb-2 mb-lg-0">


                    <li

                            class="nav-item">


                        <a

                                class="nav-link active"

                                aria-current="page" href="{% url 'flight:feed' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'flight:all_flights' %}">All flights</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'flight:search_flight_by_date' %}">Search flight by Date</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'flight:search_flight' %}">Search flight by Airport</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href={% url "ticket:list_of_all_ticket_for_user" %}>My Tickets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href={% url "ticket:record_of_tickets" %}>My Billing</a>
                    </li>
                    {% if user.role == 'agency' %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'flight:create_flight' %}">Create Flight</a>
                        </li>
                    {% endif %}
                    {% if user.role == 'agency' %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'flight:crate_airplane' %}">Create Airplane</a>
                        </li>
                    {% endif %}

                    {% if user.role == 'agency' %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'flight:create_airport' %}">Create Airway</a>
                        </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:profile' %}">My Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:charging_account' %}">Charging Account</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href={% url "user:logout" %}>Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "user:login" %}">Log In</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<main class="container">
</main>
{% block content %}
{% endblock %}
</body>
</html>

templates/home.html
{#    {% block content %}#}
{#    <style>#}
{#        .home-container{#}
{#            display: grid;#}
{#            grid-template-columns: 1fr 3fr;#}
{#        }#}
{#    </style>#}
{#        <h1>Home Page</h1>#}
{##}
{#        <div class="home-container">#}
{#            {% if user.is_authenticated %}#}
{#            <h1 class="title">Hello, my friend named <span>{{ user.username }}</span> </h1>#}
{#            <h1 class="title">Your Charge : <span>{{ user.charge }} 💵</span> </h1>#}
{#            {% endif %}#}
{#        </div>#}
{##}
{#    {% endblock %}#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FlySwift</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: white;
            background-size: cover;
            font-family: Arial, sans-serif;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }

        nav {
            background-color: #333;
            padding: 10px;
            text-align: center;
        }


        .logo {
            max-width: 50px;
            max-height: 50px;
        }

        hr {
            border: 1px solid #ccc;
            margin: 20px 0;
        }

        .home-container {
            display: grid;
            grid-template-columns: 1fr 3fr;
            padding: 20px;
            color: white;
        }

        .title {
            font-size: 24px;
            margin-bottom: 10px;
        }
    </style>
</head>
<body style="">

<header>
    {% include 'header.html' %}
</header>

<hr>

<div class="home-container">
    {% if user.is_authenticated %}
        <h1 class="title text-black">Hello, my friend named <span class="text-black">{{ user.username }}</span></h1>
        <h1 class="title text-black">Your Charge: <span class="text-black">{{ user.charge }} 💵</span></h1>
    {% endif %}
</div>

</body>

</html>

templates/login.html
{% block content %}

<form class="form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" id="submit">Login</button>
    <a href="{% url 'user:signup' %}">
      Register
  </a>
</form>

{% endblock %}

templates/logout.html
{% block content %}

<h1>You have logued out</h1>

{% endblock %}

templates/profile.html
<!DOCTYPE html>
<html>
<head>
    <title>User Profile Details</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            padding: 20px;
        }

        .profile-section {
            margin-bottom: 20px;
        }

        .profile-section {
            margin-bottom: 20px;
            padding: 15px;
            border: 1px solid #ddd;
            border-radius: 5px;
            background-color: #f8f9fa; /* Light, subtle background  */
        }

        .btn-centered {
            text-align: center;
            display: block; /* Makes it take up the full width */
            margin-top: 10px; /* Adjust spacing as needed */
        }
    </style>
</head>
<body>
<div class="container">
    <h1>User Profile</h1>

    <div class="profile-section">
        <p><strong>Full Name:</strong> {{ user.full_name }}</p>
        <p><strong>Username:</strong> {{ user.username }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>Phone:</strong> {{ user.phone }}</p>
        <p><strong>Gender:</strong> {{ user.gender }}</p>
        <p><strong>Role:</strong> {{ user.role }}</p>
        <p><strong>Charge:</strong> {{ user.charge }}</p>
        <p><strong>Address:</strong> {{ user.address }}</p>
        <p><strong>User unique:</strong> {{ user.pid }}</p>
        <p><strong>Last login:</strong> {{ user.last_login }}</p>
        {% if token %}
            <p><strong>Your token:</strong> {{ token }}</p>
        {% endif %}
    </div>
    <form method="POST" href="{% url 'user:profile' %}">
        {% csrf_token %}

        <button type="submit" class="btn btn-secondary">
            Generate Token
        </button>
    </form>
    <div class="ticket-container">
        <a href="{% url "flight:feed" %}" class="btn btn-primary btn-centered">Back to Home</a>
    </div>
</div>
</body>
</html>