FlySwift/urls.py
from django.contrib import admin
from django.urls import path, include
from flight.views import index

urlpatterns = [
    path("", index, name="main page"),
    path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('ticket/', include('ticket.urls')),
    path('flight/', include('flight.urls')),
]

flight/urls.py
from django.urls import path

from flight import views

app_name = "flight"

urlpatterns = [
    path('', views.index, name='feed'),
    path("all/", views.FlightListView.as_view(), name="all_flights"),
    path("search/", views.search_flights, name="search_flight"),
    path('detail/<int:flight_id>', views.FlightView.as_view(), name="each_flight_page"),
    path("create/", views.FlightCreateView.as_view(), name="create_flight"),
    path("user_tickets/", views.user_tickets, name="user_tickets"),
    path("create/airport/", views.create_airport, name="create_airport"),
    path("create/airplane/", views.CreateAirplaneView.as_view(), name="crate_airplane"),
    path('search/date/', views.search_flights_byDate, name="search_flight_by_date"),
    path("allFlight/", views.getAllFlightrest.as_view(), name="all_flight_by_rest"),
    path("specificFlight/", views.search_flight_byDate_api.as_view(), name="get_specific_flights"),
]

ticket/urls.py
from django.urls import path

from .views import list_tickets, buying_ticket_page, cancelTicket, list_record_of_tickets, TicketDetailView, \
    TicketDetailViewAll, CheckTicket

app_name = "ticket"
urlpatterns = [
    path('all/', list_tickets, name="list_of_all_ticket_for_user"),
    path('buy/<int:fpk>/', buying_ticket_page.as_view(), name='buying_ticket'),
    path("cancel/<int:tpk>/", cancelTicket.as_view(), name="cancel_ticket"),
    path("record/", list_record_of_tickets, name="record_of_tickets"),
    path('ticket/<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('check/', CheckTicket.as_view(), name="check_ticket")
]

user/urls.py
from django.urls import path

from user.views import UserSignUp, Logout, Login, ChargingAccount, user_info

app_name = "user"

urlpatterns = [
    path('signup/', UserSignUp.as_view(), name="signup"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('charge/', ChargingAccount.as_view(), name="charging_account"),
    path('profile/', user_info.as_view(), name='profile'),
]

ticket/models.py
import uuid

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

import flight
import user.models
from flight.models import Flight
from user.models import MyUserModel
from .manager import TicketManger

string_checker = "No user reserved"


class Seats(models.Model):
    flightID = models.ForeignKey(Flight, on_delete=models.CASCADE, related_name="Flight_rel",
                                 verbose_name="id to flight", null=True , blank=True)
    userReserved = models.ForeignKey(MyUserModel, on_delete=models.CASCADE, related_name="user_rel",
                                     verbose_name="id to user", null=True , blank=True)
    seatNumber = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)], null=True,
                                             blank=True)
    isReserved = models.BooleanField(default=False, blank=True)


class Ticket(models.Model):
    user = models.ForeignKey(MyUserModel, on_delete=models.CASCADE, related_name="tickets", blank=True, null=True)
    flight = models.ForeignKey(Flight, on_delete=models.CASCADE, related_name="flight", blank=True, null=True)
    price = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(999999999)], null=True,
                                        blank=True)
    unique_id = models.CharField(max_length=500, default='', blank=True, null=True)
    active = models.BooleanField(default=True, verbose_name="being status : ")
    seatID = models.ForeignKey(Seats, on_delete=models.DO_NOTHING, verbose_name="seat ticket id", blank=True, null=True)
    tickets = TicketManger()
    objects = models.Manager()

    def save(self, *args, **kwargs):
        # self.unique_id = f'{self.user}-{self.flight.id}-{self.flight.__str__()}-{self.seatID.seatNumber}-{self.flight.airplane.id}-{self.flight.arrival}'\
        self.unique_id = uuid.uuid4().__hash__()
        # self.id = uuid.uuid4().__hash__()

        super(Ticket, self).save(*args, **kwargs)

    def __str__(self):
        return f"Ticket ( {self.unique_id} ) for {self.user.full_name} with sent number : {self.seatID.seatNumber} on flight {self.flight}"

ticket/forms.py
from django import forms
from django.core.exceptions import ValidationError

class CreditCardForm(forms.Form):
    credit_card_number = forms.IntegerField(label="Credit card number")
    credit_card_holder_name = forms.CharField(required=True, max_length=40)
    expiration_month = forms.IntegerField(label="Expiration month (MM)")
    expiration_year = forms.IntegerField(label="Expiration year (YYYY)")
    cvv = forms.IntegerField(label="CVV")
    seat_number = forms.IntegerField(min_value=1, label="seat_number")

    def clean(self):
        cleaned_data = super().clean()

        # Validate the expiration date
        month = cleaned_data['expiration_month']
        year = cleaned_data['expiration_year']
        ccn = cleaned_data['credit_card_number']
        ccv_number = cleaned_data['cvv']
        if not (1 <= month <= 12):
            raise Exception({'invalid expiration_month'})

        if not (2023 <= year <= 2030):
            raise Exception({'invalid expiration_year'})
        if not (1000000000000000 <= ccn <= 9999999999999999):
            raise Exception({"invalid credit_card_number"})
        if not (100 <= ccv_number <= 999):
            raise Exception({"invalid cvv_number"})
        return cleaned_data

ticket/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.core.validators import BaseValidator
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView

from flight.models import Flight
from user.models import MyUserModel
from .forms import CreditCardForm
from .models import Ticket, Seats
from django.core.mail import EmailMessage
from recorder.models import recordOfTickets

log = logging.getLogger(__name__)


# @login_required(login_url="http://localhost:8000/user/login/")
# def create_ticket(request):
#     try:
#         if request.method == 'POST':
#             form = TicketForm(request.POST)
#             if form.is_valid():
#                 form.save()
#                 log.info(f"ticket saved -> {form.id}")
#                 return redirect('list_of_all_ticket')
#         else:
#             form = TicketForm()
#
#     except Exception as e:
#         log.error(str(e))
#     context = {'form': form}
#     return render(request, 'tickets/create.html', context)


def send_welcome_email(user_email, ticket_messsage):
    subject = 'Report of ticket purchasing'
    message = ticket_messsage
    from_email = user_email
    recipient_list = user_email
    msg = EmailMessage(subject,
                       message, to=[from_email])
    msg.send()
    log.info(f"message send : {msg.subject}")


class TicketDetailView(DetailView):
    model = Ticket
    template_name = 'tickets/ticket_detail.html'  # Adjust the template path as needed

    def get_object(self, queryset=None):
        """
        Overriding this method to check if the requesting user owns the ticket.
        """
        ticket = super().get_object(queryset)
        if ticket.user != self.request.user:
            raise Http404("You are not authorized to view this ticket.")
        return ticket


class TicketDetailViewAll(View):
    model = Ticket
    template_name = 'tickets/ticket_detail.html'  # Adjust the template path as needed

    def get(self, request, *args, **kwargs):
        ticket_id = kwargs["ticketNumber"]
        template = loader.get_template(self.template_name)
        try:
            ticket = Ticket.objects.get(pk=ticket_id)
            if ticket:
                return HttpResponse(template.render({'ticket': ticket}, request))
            else:
                return HttpResponse("404 , not found")
        except Exception as e:
            return HttpResponse(template.render({"error": 'Ticket does not exist'}, request))


def list_tickets(request):
    if request.user.is_authenticated:
        requested_user = request.user.id
        tickets = Ticket.objects.filter(Q(user=requested_user), active=True)
        context = {'tickets': tickets}
        return render(request, 'tickets/ticket_list.html', context)
    else:
        return render(request, "login.html", {})


# Importtant
def list_record_of_tickets(request):
    requested_user = request.user.id
    tickets = Ticket.objects.filter(Q(user=requested_user))
    context = {'tickets': tickets}
    return render(request, 'tickets/ticket_record.html', context)


class FlightDoesNotExist:
    pass


class cancelTicket(LoginRequiredMixin, View):
    login_url = "user:login"

    def get(self, request, *args, **kwargs):
        ticket_key = kwargs["tpk"]
        ticket = Ticket.objects.get(pk=ticket_key)
        user = MyUserModel.objects.get(pk=request.user.id)
        flight = Flight.objects.get(pk=ticket.flight_id)
        user.charge = int(user.charge) + (
                int(ticket.price) - (int(ticket.price) * ((100 - int(flight.cost_of_cancel)) / 100)))
        ticket.active = False
        user.save()
        ticket.save()
        return redirect("flight:feed")


class buying_ticket_page(LoginRequiredMixin, View):
    template_name = 'tickets/buying.html'
    login_url = "user:sign-in"

    def get(self, request, *args, **kwargs):
        flight_pk = kwargs["fpk"]
        template = loader.get_template(self.template_name)
        try:
            flight = Flight.objects.get(pk=flight_pk)
            if flight:
                credit_card_form = CreditCardForm()
                return HttpResponse(template.render({'flight': flight, "forms": credit_card_form}, request))
            else:
                return HttpResponse("404 , not found")
        except ObjectDoesNotExist:
            return HttpResponse("404 , not found")

    def post(self, request, *args, **kwargs):
        credit_card_value = CreditCardForm(request.POST)
        user = MyUserModel.objects.get(pk=request.user.id)
        flight = Flight.objects.get(pk=kwargs["fpk"])
        try:
            if credit_card_value.is_valid() and request.user.id and flight:
                seat_object = get_object_or_404(Seats, flightID=kwargs["fpk"], seatNumber=request.POST["seat_number"])
                if seat_object and not seat_object.isReserved:
                    seat_object.isReserved = True
                    seat_object.userReserved = request.user
                    seat_object.save()
                    result = Ticket.objects.create(user=user, flight=flight, price=int(flight.price),
                                                   seatID=seat_object)
                    result.save()
                    flight.count_of_reserved = flight.count_of_reserved + 1
                    flight.save()
                    recordOfTickets(credit_card_name=request.POST.get("credit_card_holder_name"),
                                    credit_card_month=request.POST.get("expiration_month"),
                                    credit_card_number=request.POST.get("credit_card_number"),
                                    credit_card_year=request.POST.get("expiration_year"),
                                    credit_card_ccv=request.POST.get("cvv"), ticket=result).save()

                    send_welcome_email(user.email, result.__str__())
                    log.info(f"flight {flight.id} saved")
                    return redirect('ticket:ticket_detail', pk=result.id)
                else:
                    return render(request, "tickets/buying.html",
                                  {'flight': Flight.objects.get(pk=kwargs["fpk"]), "forms": credit_card_value,
                                   'form_errors': "Your seat has been reserved , please try another seat "})
        except Exception as e:
            print("e => " + e.__str__())
            return render(request, "tickets/buying.html",
                          {'flight': Flight.objects.get(pk=kwargs["fpk"]), "forms": credit_card_value,
                           'form_errors': e})


class CheckTicket(View):
    template_name = "tickets/check_ticket.html"

    def get(self, request):
        return render(request, "tickets/check_ticket.html")

    def post(self, request, *args, **kwargs):
        print(request.POST)
        ticket_id = request.POST["ticketNumber"]
        try:
            ticket = Ticket.objects.get(pk=ticket_id)
            if ticket:
                return render(request, "tickets/ticket_detail.html", {'ticket': ticket})
            else:
                return render(request, "tickets/check_ticket.html", {'error': "Ticket not found"})
        except Exception as e:
            return render(request, "tickets/check_ticket.html", {'error': e})

templates/tickets/buying.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buying Ticket</title>
    <style>
        body {
            font-family: sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 90%;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }

        h1 {
            text-align: center;
            font-size: 30px;
            margin-bottom: 20px;
        }

        .flight {
            margin-bottom: 20px;
        }

        .flight p {
            margin-bottom: 5px;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"] {
            width: calc(100% - 22px); /* Adjust input width */
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-bottom: 10px;
        }

        input[type="submit"] {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            display: block;
            margin: 0 auto;
        }

        .credit-card-container {
            margin-top: 20px;
            text-align: center;
        }

        .credit-card-form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }

        .alert-danger {
            background-color: #dc3545;
            color: #fff;
            padding: 10px;
            border: 1px solid #dc3545;
            border-radius: 5px;
        }
    </style>
</head>
<body>
{#<header>#}
{#    {% include 'header.html' %}#}
{#</header>#}
<div class="container">
    <h1>Buying Ticket</h1>
    <div class="flight">
        <p class="user__info"></p>
        <p class="flight__origin">Origin: {{ flight.origin }}</p>
        <p class="flight__destination">Destination: {{ flight.destination }}</p>
        <p class="flight__departure">Departure: {{ flight.departure }}</p>
        <p class="flight__arrival">Arrival: {{ flight.arrival }}</p>
        <p>Price: {{ flight.price }}</p>
    </div>
</div>

<div class="credit-card-container">
    <div class="credit-card-form">
        <h2>Credit Card Information</h2>
        {% if form_errors %}
            <ul>
                <li>{{ form_errors |escape }}</li>
            </ul>
        {% endif %}
        <form id="creditCardForm" action="{% url 'ticket:buying_ticket'  flight.id %}" method="POST">
            {% csrf_token %}


            <label for="seat_number">seat_number:</label>
            <input type="text" id="seat_number" name="seat_number" required><br>
            <label for="credit_card_number">Card Number:</label>
            <input type="text" id="credit_card_number" name="credit_card_number" required><br>
            <label for="credit_card_holder_name">Cardholder Name:</label>
            <input type="text" id="credit_card_holder_name" name="credit_card_holder_name" required><br>
            <label for="expiration_year">Expiry Year:</label>
            <input type="text" id="expiration_year" name="expiration_year" required><br>
            <label for="expiration_month">Expiry Month:</label>
            <input type="text" id="expiration_month" name="expiration_month" required><br>
            <label for="cvv">CVV:</label>
            <input type="text" id="cvv" name="cvv" required><br>
            {% for error in form.errors %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
            <input type="submit" value="Submit">
        </form>
    </div>
</div>
</body>
{#{% include 'footer.html' %}#}

</html>

templates/tickets/check_ticket.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ticket Information Input</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">
  <style>
    body {
      background-color: #f2f2f2;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
    }

    .container {
      background-color: #fff;
      border-radius: 10px;
      padding: 30px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .input-group {
      margin-bottom: 15px;
    }

    .input-group label {
      display: block;
      margin-bottom: 5px;
    }

    .btn-primary {
      background-color: #007bff;
      border-color: #007bff;
    }
  </style>
</head>
<body>
  <div class="container">
      {% if error %}
          <h2>{{ error }}</h2>
      {% endif %}
    <h1>Enter Ticket Number</h1>
    <form method="post" id="ticketForm" href="ticket:check_ticket">
        {% csrf_token %}
      <div class="input-group mb-3">
        <label for="ticketNumber" class="form-label">Ticket Number</label>
        <input type="text" class="form-control" id="ticketNumber" name="ticketNumber" placeholder="Enter your ticket number" required>
      </div>
      <button type="submit" class="btn btn-primary">View Ticket Information</button>
    </form>
  </div>

</body>
</html>

templates/tickets/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Ticket</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<header>
    {% include 'header.html' %}
</header>
<div class="container">
    <h1>Create Ticket</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create Ticket</button>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
{% include 'footer.html' %}

</html>

templates/tickets/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<header>
    {% include 'header.html' %}
</header>
<div class="container">
    <h1>Your Ticket</h1>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>User</th>
                <th>Seat Number</th>
                <th>Flight</th>
                <th>Back to main menu</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ ticket.user }}</td>
                <td>{{ ticket.seat_number }}</td>
                <td>{{ ticket.flight }}</td>
                <td><a href="{% url 'flight:feed' %}">Main Page</a></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
</body>
{% include 'footer.html' %}

</html>

templates/tickets/ticket_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket Details</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .ticket-container {
            border: 1px solid #ccc;
            padding: 20px;
            margin-top: 30px;
            border-radius: 5px;
        }

        .btn-centered {
            text-align: center;
            display: block; /* Makes it take up the full width */
            margin-top: 10px; /* Adjust spacing as needed */
        }
    </style>
</head>
<body>
<div class="container">
    <h1>Ticket Details</h1>
    {% if error %}
        <h1>Your ticket did not found</h1>
    {% endif %}
    {% if ticket %}

        <div class="ticket-container">
            <p><strong>Ticket ID:</strong> {{ ticket.id }}</p>
            <p><strong>User:</strong> {{ ticket.user }}</p>
            <p><strong>Flight:</strong> {{ ticket.flight }}</p>
            <p><strong>Seat Number:</strong> {{ ticket.seatID.seatNumber }}</p>
            <p><strong>Price:</strong> ${{ ticket.price }}</p>
            <p><strong>Unique ID:</strong> {{ ticket.unique_id }}</p>
            <p><strong>Status:</strong>
                {% if ticket.active %}
                    Active
                {% else %}
                    Inactive
                {% endif %}
            </p>
        </div>
    {% endif %}
    <div class="ticket-container">
        <a href="{% url "flight:feed" %}" class="btn btn-primary btn-centered">Back to Home</a>
    </div>
</div>
</body>
</html>

templates/tickets/ticket_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
<header>
    {% include 'header.html' %}
</header>

{% csrf_token %}
<div class="container">
    <h1>Ticket List</h1>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Ticket ID</th>
            <th>User</th>
            <th>Flight</th>
            <th>Seat Number</th>
            <th>Price</th>
            <th>Cancel this ticket ?</th>
            <th>Show more information</th>
        </tr>
        </thead>
        <tbody>
        {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.id }}</td>
                <td>{{ ticket.user }}</td>
                <td>{{ ticket.flight }}</td>
                <td>{{ ticket.seatID.seatNumber }}</td>
                <td>{{ ticket.price }}</td>
                <td><a href="{% url 'ticket:cancel_ticket' tpk=ticket.id %}">Cancel</a></td>
                <td><a href="{% url 'ticket:ticket_detail' pk=ticket.id %}">Info ...</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{#{% include 'footer.html' %}#}

</body>

templates/tickets/ticket_record.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<header>
    {% include 'header.html' %}
</header>
{% csrf_token %}
<div class="container">
    <h1>Ticket List</h1>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Ticket ID</th>
            <th>User</th>
            <th>Flight</th>
            <th>Seat Number</th>
            <th>Price</th>
            <th>active</th>
        </tr>
        </thead>
        <tbody>
        {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.id }}</td>
                <td>{{ ticket.user }}</td>
                <td>{{ ticket.flight }}</td>
                <td>{{ ticket.seatID.seatNumber }}</td>
                <td>{{ ticket.price }}</td>
                <td>{{ ticket.active }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{#{% include 'footer.html' %}#}

</body>

templates/tickets/user_tickets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Ticket</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<header>
    {% include 'header.html' %}
</header>
<div class="container">
    <h1>Your Ticket</h1>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Origin</th>
            <th>Destination</th>
            <th>Departure</th>
            <th>Arrival</th>
            <th>Plane</th>
            <th>Seat Number</th>
            <th>Price</th>
            <th>Cancel</th>
        </tr>
        </thead>
        <tbody>
        {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.flight.origin }}</td>
                <td>{{ ticket.flight.destination }}</td>
                <td>{{ ticket.flight.departure }}</td>
                <td>{{ ticket.flight.arrival }}</td>
                <td>{{ ticket.flight.airplane }}</td>
                <td>{{ ticket.seat_number }}</td>
                <td>{{ ticket.price }}</td>
                <td><a href="{% url 'ticket:cancel_ticket'  tpk=ticket.id %}">Cancel This</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
{#{% include 'footer.html' %}#}

</html>