FlySwift/urls.py
from django.contrib import admin
from django.urls import path, include
from flight.views import index

urlpatterns = [
    path("", index, name="main page"),
    path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('ticket/', include('ticket.urls')),
    path('flight/', include('flight.urls')),
]

ticket/urls.py
from django.urls import path

from .views import list_tickets, buying_ticket_page, cancelTicket, list_record_of_tickets, TicketDetailView, \
    TicketDetailViewAll, CheckTicket

app_name = "ticket"
urlpatterns = [
    path('all/', list_tickets, name="list_of_all_ticket_for_user"),
    path('buy/<int:fpk>/', buying_ticket_page.as_view(), name='buying_ticket'),
    path("cancel/<int:tpk>/", cancelTicket.as_view(), name="cancel_ticket"),
    path("record/", list_record_of_tickets, name="record_of_tickets"),
    path('ticket/<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('check/', CheckTicket.as_view(), name="check_ticket")
]

user/urls.py
from django.urls import path

from user.views import UserSignUp, Logout, Login, ChargingAccount, user_info

app_name = "user"

urlpatterns = [
    path('signup/', UserSignUp.as_view(), name="signup"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('charge/', ChargingAccount.as_view(), name="charging_account"),
    path('profile/', user_info.as_view(), name='profile'),
]

templates/authoriziation/charging.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buying Ticket</title>
    <style>
        body {
            font-family: sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 90%;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
        }

        h1 {
            text-align: center;
            font-size: 30px;
            margin-bottom: 20px;
        }

        .flight {
            margin-bottom: 20px;
        }

        .flight p {
            margin-bottom: 5px;
        }

        label {
            display: block;
            margin-bottom: 5px;
        }

        input[type="text"] {
            width: calc(100% - 22px); /* Adjust input width */
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-bottom: 10px;
        }

        input[type="submit"] {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            display: block;
            margin: 0 auto;
        }

        .credit-card-container {
            margin-top: 20px;
            text-align: center;
            padding-bottom: 60px; /* Adjust the padding to accommodate the fixed footer height */
    /* Additional styles */
        }

        .credit-card-form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
            padding-bottom: 60px; /* Adjust the padding to accommodate the fixed footer height */
            /* Additional styles */
        }

        }

        .alert-danger {
            background-color: #dc3545;
            color: #fff;
            padding: 10px;
            border: 1px solid #dc3545;
            border-radius: 5px;
        }
    </style>
</head>
<body>
<header>
    {% include 'header.html' %}
</header>
<div class="credit-card-container">
    <div class="credit-card-form">
        <h2>Credit Card Information</h2>
        <form id="creditCardForm" action="{% url 'user:charging_account' %}" method="post">
            {% csrf_token %}

            <label for="bill">How much do you want to charge:</label>
            <input type="text" id="bill" name="bill" required><br>
            <label for="credit_card_number">Card Number:</label>
            <input type="text" id="credit_card_number" name="credit_card_number" required><br>
            <label for="credit_card_holder_name">Cardholder Name:</label>
            <input type="text" id="credit_card_holder_name" name="credit_card_holder_name" required><br>
            <label for="expiration_year">Expiry Year:</label>
            <input type="text" id="expiration_year" name="expiration_year" required><br>
            <label for="expiration_month">Expiry Month:</label>
            <input type="text" id="expiration_month" name="expiration_month" required><br>
            <label for="cvv">CVV:</label>
            <input type="text" id="cvv" name="cvv" required><br>
            {% for error in form.errors %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
            <input type="submit" value="Submit">
        </form>
    </div>
</div>
</body>
{% include 'footer.html' %}

</html>

templates/authoriziation/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            font-family: sans-serif;
            text-align: center;
            background-color: #f5f5f5; /* Add a subtle background color */
        }

        .container {
            width: 50%;
            margin: 50px auto; /* Add some top margin */
            padding: 30px;
            border: 1px solid #ccc;
            background-color: #fff; /* Form has a white background */
            box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: 600;
        }

        input, select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        button {
            padding: 10px 20px;
            border: none;
            background-color: #007bff;
            color: white;
            cursor: pointer;
            border-radius: 5px;
            transition: background-color 0.3s ease; /* For a smooth hover effect */
        }

        button:hover {
            background-color: #0056b3; /* Slightly darker on hover */
        }


    </style>
</head>
<body>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1>Login</h1>
            <form action="" method="post" href={% url "user:login" %}>
                {% csrf_token %}
                {% if message %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% endif %}
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Login</button>
            </form>
        </div>
    </div>
</div>
<button type="submit" id="signup"><a href={% url "user:signup" %}>Sign Up</a></button>
<button type="submit" id="check-ticket"><a href={% url "ticket:check_ticket" %}>Check Ticket</a></button>

</body>

</html>

templates/authoriziation/signup.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <style>
        body {
            font-family: sans-serif;
            text-align: center;
            background-color: #f5f5f5; /* Add a subtle background color */
        }

        .container {
            width: 50%;
            margin: 50px auto; /* Add some top margin */
            padding: 30px;
            border: 1px solid #ccc;
            background-color: #fff; /* Form has a white background */
            box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: 600;
        }

        input, select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        button {
            padding: 10px 20px;
            border: none;
            background-color: #007bff;
            color: white;
            cursor: pointer;
            border-radius: 5px;
            transition: background-color 0.3s ease; /* For a smooth hover effect */
        }

        button:hover {
            background-color: #0056b3; /* Slightly darker on hover */
        }

        .error-messages {
            background-color: #ffe0e0; /* Light red background */
            border: 1px solid #f00; /* Red border */
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px; /* Slightly rounded corners*/
        }


    </style>
</head>
<body>

<div class="container">
    <h1>Sign Up</h1>
    {% if message %}
        <div class="error-messages">
            <h1>{{ message }}</h1>
        </div>
    {% endif %}
    <form action="{% url 'user:signup' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
        </div>

        <div class="form-group">
            <label for="password1">Password:</label>
            <input type="password" id="password1" name="password1" required>
        </div>

        <div class="form-group">
            <label for="password2">Password Confirm:</label>
            <input type="password" id="password2" name="password2" required>
        </div>

        <div class="form-group">
            <label for="full_name">Full Name:</label>
            <input type="text" id="full_name" name="full_name" required>
        </div>

        <div class="form-group">
            <label for="email">Email:</label>
            <input type="text" id="email" name="email" required>
        </div>

        <div class="form-group">
            <input type="tel" id="phone" name="phone" maxlength="11" required>
            <label for="phone">Phone Number (Format: 0912-345-6789)</label>
        </div>

        <div class="form-group">
            <input type="text" id="address" name="address" required>
            <label for="address">Address: </label>
        </div>

        <div class="form-group">
            <label for="country">Country:</label>
            <select name="country" id="country">
                {% for country in formatted_countries %}
                    <option value="{{ country.code }}">{{ country.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="gender">Gender:</label>
            <select id="gender" name="gender">
                <option value="male">male</option>
                <option value="female">female</option>
            </select>
        </div>

        <div class="form-group">
            <label for="role">Role:</label>
            <select id="role" name="role">
                <option value="normal">Normal</option>
                <option value="agency">Agency</option>
            </select>
        </div>
        <input type="submit" value="Submit">

    </form>
</div>
<button type="submit"><a href={% url "user:login" %}>Login</a></button>
<button type="submit" id="check-ticket"><a href={% url "ticket:check_ticket" %}>Check Ticket</a></button>

</body>
{% include 'footer.html' %}

</html>